### ISSUE TITLE
I have the following error, while using FletNavigator on Replit server

### ISSUE THREAD

**Issue by jvalle63** [xzripper/flet_navigator#16]
**Describe your problem:**
I found this log errors..

2024-08-02 14:03:39.19
self.__pubsub.unsubscribe_all(self.__session_id)
2024-08-02 14:03:39.19
File "/home/runner/210bc72a-01ef-4102-9a2c-bcda7b2ed004/.pythonlibs/lib/python3.10/site-packages/flet_runtime/pubsub.py", line 143, in unsubscribe_all
2024-08-02 14:03:39.19
self.__unsubscribe(session_id)
2024-08-02 14:03:39.19
File "/home/runner/210bc72a-01ef-4102-9a2c-bcda7b2ed004/.pythonlibs/lib/python3.10/site-packages/flet_runtime/pubsub.py", line 158, in __unsubscribe
2024-08-02 14:03:39.19
self.__subscribers.pop(session_id)
2024-08-02 14:03:39.19
KeyError: '604288ce-3913-4b59-ba31-b89be2831465'
2024-08-02 14:29:08.09
Exception in thread Thread-3801 (on_event):
2024-08-02 14:29:08.09
Traceback (most recent call last):
2024-08-02 14:29:08.09
File "/nix/store/rwxj49zghamyhy07b67yhiq64bmznvmm-python3-3.10.14/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2024-08-02 14:29:08.19
self.run()
2024-08-02 14:29:08.19
File "/nix/store/rwxj49zghamyhy07b67yhiq64bmznvmm-python3-3.10.14/lib/python3.10/threading.py", line 953, in run
2024-08-02 14:29:08.19
self._target(*self._args, **self._kwargs)
2024-08-02 14:29:08.19
File "/home/runner/210bc72a-01ef-4102-9a2c-bcda7b2ed004/.pythonlibs/lib/python3.10/site-packages/flet_runtime/app.py", line 347, in on_event
2024-08-02 14:29:08.19
page._close()
2024-08-02 14:29:08.19
File "/home/runner/210bc72a-01ef-4102-9a2c-bcda7b2ed004/.pythonlibs/lib/python3.10/site-packages/flet_core/page.py", line 394, in _close
2024-08-02 14:29:08.19
self.__pubsub.unsubscribe_all()
2024-08-02 14:29:08.19
File "/home/runner/210bc72a-01ef-4102-9a2c-bcda7b2ed004/.pythonlibs/lib/python3.10/site-packages/flet_runtime/pubsub.py", line 241, in unsubscribe_all
2024-08-02 14:29:08.39
self.__pubsub.unsubscribe_all(self.__session_id)
2024-08-02 14:29:08.39
File "/home/runner/210bc72a-01ef-4102-9a2c-bcda7b2ed004/.pythonlibs/lib/python3.10/site-packages/flet_runtime/pubsub.py", line 143, in unsubscribe_all
2024-08-02 14:29:08.49
self.__unsubscribe(session_id)
2024-08-02 14:29:08.49
File "/home/runner/210bc72a-01ef-4102-9a2c-bcda7b2ed004/.pythonlibs/lib/python3.10/site-packages/flet_runtime/pubsub.py", line 158, in __unsubscribe
2024-08-02 14:29:08.49
self.__subscribers.pop(session_id)
2024-08-02 14:29:08.49
KeyError: '54a3968b-8b6f-4f85-a3d0-01ccedfaed37'

Then I asked the Replit AI what was going on:

It looks like you are encountering a KeyError in your code related to the Flet library specifically within the 
 file when trying to unsubscribe a session using self.__subscribers.pop(session_id). This error occurs when attempting to remove a session ID that does not exist in the 
 dictionary.

Here's a high-level plan to handle the issue:

Check if session ID exists: Before calling self.__subscribers.pop(session_id), verify that session_id exists in the 
 dictionary.
Logging: Add appropriate logging to see which session_id caused the error.
Debugging: Consider adding debugging information to understand why the session is attempted to be unsubscribed multiple times or not present.
Let's implement these changes in the __unsubscribe method:

class PubSub:
    # ... other methods ...
    def __unsubscribe(self, session_id):
        if session_id in self.__subscribers:
            self.__subscribers.pop(session_id)
        else:
            # Log or handle the missing session id case
            print(f"Attempted to unsubscribe a non-existent session_id: {session_id}")
            # Optionally raise a custom exception or handle as needed
Note:
The __unsubscribe method is taken directly from your stack trace, but you might need to adapt the implementation to your codebase or style guidelines. The PubSub class should include appropriate imports and error handling mechanisms depending on your application's logging and debugging setup.

This implementation will prevent the KeyError by checking for the presence of session_id and provide a debug message that could help trace why a session ID that doesn't exist was attempted to be unsubscribed

**Reproducing the problem:**
Code..

**Media (optional):**
Screenshot or video..

**flet_navigator version, flet version, OS:**
`FletNavigator version, Flet Version, OS..`
FN_version = 2.8.5
Flet_version = 0.23.2
OS = Linux/Poetry
**Additional:**
...

**Comment by xzripper** [comment]
I'm currently investigating in this issue, but to say ahead of time I don't think its FletNavigator issue because error happens in flet_core and flet_runtime, approximately in `Page` class, where `__subcribers` dictionary used, but FletNavigator actually doesn't manipulates with this dictionary and uses only superficial Flet methods like `page.go` or `page.update`. Can you send the code where this issue happens?

**Comment by xzripper** [comment]
It's odd issue, I can't even find `pubsub.py` file in Flet source code.

**Comment by jvalle63** [comment]
I can send the code, for sure, but it has 2600 lines. Is it ok for you?

**Comment by xzripper** [comment]
Hm, maybe only part of the code where issue happens? But if you don't know where is the issue, you can send me the code.

**Comment by jvalle63** [comment]
I think I found the problem... It was a version problem between Flet and some other problem. I update Flet with Poetry and the error vanished. For while...

Once more, thanks a lot for your help.

**Comment by xzripper** [comment]
Glad your issue got fixed :)
